import { suggestions } from '../content'
import type { Composer } from '../useChat'
import { Thumb } from './Thumb'

type Props = {
  composer: Composer
  /** The chips hide once the conversation has started. */
  started: boolean
  onSubmit: () => void
}

export function Dock({ composer, started, onSubmit }: Props) {
  return (
    <div className="dock">
      <div className={'suggestions' + (started ? ' is-hidden' : '')} id="suggestions">
        {suggestions.map((s) => (
          <a key={s.title} className="sugg" href={s.href} target="_blank" rel="noopener">
            <Thumb src={s.img} />
            <span className="sugg__body">
              <span className="sugg__tag">{s.tag}</span>
              <span className="sugg__title">{s.title}</span>
              <span className="sugg__sub">{s.sub}</span>
            </span>
          </a>
        ))}
      </div>

      <form className="composer" id="composer" onSubmit={(e) => { e.preventDefault(); onSubmit() }}>
        <div className={'composer__text' + (composer.empty ? ' is-empty' : '')} id="composer-text">{composer.text}</div>
        <div className="composer__bar">
          <div className="composer__tools">
            <span className="tool" title="Attachments are off here">
              <svg viewBox="0 0 24 24"><path d="m21 11-8.6 8.6a5 5 0 0 1-7-7L14 3.9a3.3 3.3 0 0 1 4.7 4.7l-8.7 8.7a1.7 1.7 0 0 1-2.4-2.4l8-8" /></svg>
            </span>
            <span className="tool" title="Tools">
              <svg viewBox="0 0 24 24"><path d="M4 7h10M18 7h2M4 17h2M10 17h10" /><circle cx="16" cy="7" r="2" /><circle cx="8" cy="17" r="2" /></svg>
            </span>
            <span className="model">
              <span className="model__dot" aria-hidden="true"></span>
              Akanksha 1.0
              <svg viewBox="0 0 24 24"><path d="m7 10 5 5 5-5" /></svg>
            </span>
          </div>
          <span className="composer__hint">Press send to ask</span>
          <button className="send" type="submit" aria-label="Send" disabled={composer.disabled}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 19V5M5 12l7-7 7 7" /></svg>
          </button>
        </div>
      </form>
      <p className="dock__meta">Replies run on natural intelligence, generated by Akanksha herself. She drinks less water than ChatGPT.</p>
    </div>
  )
}
