/**
 * Downloads the latin subsets of the two webfonts into landing/fonts/ and
 * writes landing/fonts/fonts.css.
 *
 * Self-hosting keeps the page independent of fonts.gstatic.com — the layout
 * is metric-sensitive, so a fallback render is a visible regression.
 *
 * Usage: node scripts/fetch-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const OUT = 'landing/fonts';
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const API =
  'https://fonts.googleapis.com/css2' +
  '?family=Instrument+Serif:ital@0;1' +
  '&family=Roboto+Serif:ital,opsz,wght@0,8..144,100..900;1,8..144,100..900';

/** Only the plain-latin subset is needed; the page has no extended glyphs. */
const LATIN = 'U+0000-00FF';

const FILENAME = {
  'Instrument Serif|normal': 'instrument-serif-latin.woff2',
  'Instrument Serif|italic': 'instrument-serif-italic-latin.woff2',
  'Roboto Serif|normal': 'roboto-serif-var-latin.woff2',
  'Roboto Serif|italic': 'roboto-serif-italic-var-latin.woff2',
};

const css = await fetch(API, { headers: { 'User-Agent': UA } }).then((r) => r.text());

fs.mkdirSync(OUT, { recursive: true });

const faces = [];

for (const block of css.split('@font-face').slice(1)) {
  const pick = (re) => re.exec(block)?.[1];

  const family = pick(/font-family:\s*'([^']+)'/);
  const style = pick(/font-style:\s*(\w+)/);
  const weight = pick(/font-weight:\s*([^;]+)/)?.trim();
  const url = pick(/url\((https:[^)]+)\)/);
  const range = pick(/unicode-range:\s*([^;]+)/) ?? '';

  if (!range.startsWith(LATIN)) continue;

  const file = FILENAME[`${family}|${style}`];
  if (!file) continue;

  const buf = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
  fs.writeFileSync(path.join(OUT, file), buf);
  console.log(`${file.padEnd(36)} ${(buf.length / 1024).toFixed(1)} KB`);

  faces.push({ family, style, weight, file });
}

const out = [
  '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */',
  ...faces.map(
    ({ family, style, weight, file }) => `
@font-face {
  font-family: '${family}';
  font-style: ${style};
  font-weight: ${weight};
  font-display: block;
  src: url('./${file}') format('woff2-variations');
}`,
  ),
].join('\n');

fs.writeFileSync(path.join(OUT, 'fonts.css'), `${out.trim()}\n`);
console.log(`\nwrote ${OUT}/fonts.css with ${faces.length} faces`);
